# Generated by Django 4.0.6 on 2022-07-09 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('role', models.CharField(choices=[('MC', 'Main Character'), ('SC', 'Secondary Character')], max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
        migrations.CreateModel(
            name='Insult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insult', models.CharField(max_length=200)),
                ('comeback', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Insult',
                'verbose_name_plural': 'Insults',
            },
        ),
        migrations.CreateModel(
            name='Pirate',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.character')),
                ('is_pirate', models.BooleanField(default=True)),
                ('is_captain', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pirate',
                'verbose_name_plural': 'Pirates',
            },
            bases=('app.character',),
        ),
    ]
