# Generated by Django 3.2.8 on 2021-10-06 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
        migrations.CreateModel(
            name='Pirate',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.character')),
                ('is_pirate', models.BooleanField(default=True)),
                ('is_captain', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pirate',
                'verbose_name_plural': 'Pirates',
            },
            bases=('app.character',),
        ),
    ]
