# Generated by Django 3.2.8 on 2021-10-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insult', models.CharField(max_length=200)),
                ('response', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Insult',
                'verbose_name_plural': 'Insults',
            },
        ),
    ]
