# Generated by Django 3.2.8 on 2021-10-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_insult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insult',
            old_name='response',
            new_name='comeback',
        ),
    ]
