# Generated by Django 3.2.8 on 2021-10-06 19:38

from django.db import migrations
import app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_insult_insult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insult',
            name='comeback',
            field=app.models.LowerCaseField(max_length=200),
        ),
    ]
