# Generated by Django 3.2.8 on 2021-10-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_insult_comeback'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='role',
            field=models.CharField(choices=[('MC', 'Main Character'), ('SC', 'Secondary Character')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
